name: rate

version: '3.8'

services:
  rate-postgres:
    image: rate-postgres:latest
    build: ./postgres
    container_name: rate-postgres
    restart: always
    environment:
      POSTGRES_USER: joy
      POSTGRES_PASSWORD: rate@123!
      POSTGRES_DB: rate
    ports:
      - "5432:5432"
    volumes:
      - rate_pgdata:/var/lib/postgresql/data
    networks:
      - rate-network

  rate-strapi:
    build: ./strapi
    image: rate-strapi:latest
    container_name: rate-strapi
    restart: always
    depends_on:
      - rate-postgres
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: rate-postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: rate
      DATABASE_USERNAME: joy
      DATABASE_PASSWORD: rate@123!
      API_TOKEN_SALT: tobemodified
      ADMIN_JWT_SECRET: ratebox-admin-jwt-secret
      JWT_SECRET: ratebox-jwt-secret
      APP_KEYS: key1,key2,key3,key4
      TRANSFER_TOKEN_SALT: ratebox-transfer-token-salt
    volumes:
      - ./strapi/config:/opt/app/config
      - ./strapi/src:/opt/app/src
      - ./strapi/package.json:/opt/app/package.json
      - ./strapi/yarn.lock:/opt/app/yarn.lock
      - ./strapi/public/uploads:/opt/app/public/uploads
    networks:
      - rate-network

  rate-next:
    build: ./next
    image: rate-next:latest
    container_name: rate-next
    restart: always
    depends_on:
      - rate-strapi
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:1337
      NEXT_PUBLIC_STRAPI_API_URL: http://localhost:1337
      NEXT_INTERNAL_API_URL: http://rate-strapi:1337
      IMAGE_HOSTNAME: localhost
      IMAGE_PORT: 1337
    volumes:
      - ./next/src:/opt/app/src
      - ./next/public:/opt/app/public
      - ./next/package.json:/opt/app/package.json
      - ./next/yarn.lock:/opt/app/yarn.lock
      - ./next/.env:/opt/app/.env
      - ./next/next.config.mjs:/opt/app/next.config.mjs
    networks:
      - rate-network

networks:
  rate-network:
    driver: bridge

volumes:
  rate_pgdata:
    name: rate_pgdata
