name: rate

services:
  # Service Strapi - Backend CMS
  strapi:
    image: strapi  # Tên image sẽ được build
    build:
      context: ./strapi  # Thư mục chứa Dockerfile
      dockerfile: Dockerfile  # Tên file Dockerfile
    container_name: strapi
    restart: always
    env_file:  # Sử dụng file .env
      - ./strapi/.env
    ports:
      - "1337:1337"  # Map cổng
    volumes:
      - ./strapi/config:/opt/app/config        # Mount thư mục config
      - ./strapi/src:/opt/app/src              # Mount thư mục source code
      - ./strapi/package.json:/opt/app/package.json # Mount file package.json
      - ./strapi/yarn.lock:/opt/app/yarn.lock  # Mount file yarn.lock
      - ./strapi/.env:/opt/app/.env            # Mount file .env để có thể thay đổi biến môi trường mà không cần rebuild
      - ./strapi/public/uploads:/opt/app/public/uploads # Mount thư mục uploads
    networks:
      - rate  # Kết nối mạng
    depends_on:  # Phụ thuộc vào service khác
      - rateDB  # Chỉ khởi động sau khi rateDB đã chạy

  # Service Next.js - Frontend
  next:
    image: next  # Tên image sẽ được build
    build:
      context: ./next  # Thư mục chứa Dockerfile
      dockerfile: Dockerfile  # Tên file Dockerfile
    container_name: next
    restart: always
    env_file:  # Sử dụng file .env
      - ./next/.env
    ports:
      - "3001:3001"  # Map cổng
    volumes:
      - ./next:/app  # Mount thư mục next vào container
    networks:
      - rate  # Kết nối mạng
    depends_on:  # Phụ thuộc vào service khác
      - strapi  # Chỉ khởi động sau khi strapi đã chạy

# Định nghĩa volumes
volumes:
  postgres_data:  # Volume cho PostgreSQL để lưu trữ dữ liệu

# Định nghĩa networks
networks:
  rate:
    name: Rate
    driver: bridge  # Sử dụng bridge network cho các container giao tiếp với nhau
