
services:
  rate-dedup:
    build: ./splink-service
    environment:
      - DB_CONN=postgresql+psycopg2://rate:rate@postgre:5432/rate
      - SPLINK_SETTINGS_PATH=/app/linker_settings.json
    volumes:
      - ./splink-service/linker_settings.json:/app/linker_settings.json
    ports: ["8090:8090"]
    depends_on: []
    networks:
      - Gateway

networks:
  Gateway:
    external: true
