// Catalyst UI Kit components - Modern React components built with Tailwind CSS
export { Button, TouchTarget } from '@/components/catalyst/button'
export { Link } from '@/components/catalyst/link'

// Additional components (will add as needed)
// export { Alert } from '@/components/catalyst/alert'
// export { AuthLayout } from '@/components/catalyst/auth-layout'
// export { Avatar } from '@/components/catalyst/avatar'
// export { Badge } from '@/components/catalyst/badge'
// export { Checkbox } from '@/components/catalyst/checkbox'
// export { Combobox } from '@/components/catalyst/combobox'
// export { DescriptionList, DescriptionTerm, DescriptionDetails } from '@/components/catalyst/description-list'
// export { Dialog, DialogActions, DialogBody, DialogDescription, DialogTitle } from '@/components/catalyst/dialog'
// export { Divider } from '@/components/catalyst/divider'
// export { Dropdown, DropdownButton, DropdownDivider, DropdownHeader, DropdownItem, DropdownLabel, DropdownMenu, DropdownSection, DropdownShortcut } from '@/components/catalyst/dropdown'
// export { Field, FieldGroup, Fieldset, Label, Legend } from '@/components/catalyst/fieldset'
// export { Heading } from '@/components/catalyst/heading'
// export { Input } from '@/components/catalyst/input'
// export { Listbox, ListboxLabel, ListboxOption } from '@/components/catalyst/listbox'
// export { Navbar, NavbarDivider, NavbarItem, NavbarLabel, NavbarSection, NavbarSpacer } from '@/components/catalyst/navbar'
// export { Pagination, PaginationGap, PaginationList, PaginationNext, PaginationPage, PaginationPrevious } from '@/components/catalyst/pagination'
// export { Radio, RadioField, RadioGroup } from '@/components/catalyst/radio'
// export { Select } from '@/components/catalyst/select'
// export { Sidebar, SidebarBody, SidebarFooter, SidebarHeader, SidebarHeading, SidebarItem, SidebarLabel, SidebarSection, SidebarSpacer } from '@/components/catalyst/sidebar'
// export { SidebarLayout } from '@/components/catalyst/sidebar-layout'
// export { StackedLayout } from '@/components/catalyst/stacked-layout'
// export { Switch, SwitchField, SwitchGroup } from '@/components/catalyst/switch'
// export { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/catalyst/table'
// export { Text } from '@/components/catalyst/text'
// export { Textarea } from '@/components/catalyst/textarea' 