name: Crawler
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "8191:8191"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/v1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - Rate

networks:
  Rate:
    driver: bridge
