name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install commitlint deps
        run: |
          yarn --version || npm i -g yarn@1.22.22
          yarn add -D @commitlint/cli @commitlint/config-conventional typescript ts-node

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.ts

